// Generates the embed's example loaders before `vite` / `vite build` / `tsc`:
//
//   src/embed/loaders.generated.ts   id → { lazy import, layout }
//
// Git-ignored and rebuilt on every dev start, build and typecheck, so it cannot go stale.

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadExamples, SRC } from "./examples-lib.ts";

const examples = await loadExamples();

writeFileSync(
    join(SRC, "embed", "loaders.generated.ts"),
    `// Generated by scripts/generate.ts. Do not edit; it is git-ignored.

import type { ComponentType } from "react";
import type { ExampleLayout } from "../examples/meta-types";

export const LOADERS: Record<
    string,
    { load: () => Promise<{ default: ComponentType }>; layout: ExampleLayout }
> = {
${examples
    .map(
        (e) =>
            `    ${JSON.stringify(e.slug)}: {\n        load: () => import("../examples/${e.slug}"),\n        layout: ${JSON.stringify(e.meta.layout ?? "fill")},\n    },`,
    )
    .join("\n")}
};
`,
);

console.log(`examples: ${examples.length}`);
